### ISSUE TITLE
System buffer locked

### ISSUE THREAD

**Issue by licarifrancesco** [mchehraz/screenrecorder#3]
When the application take the screenshot lock the system buffer.
If you move the window in recording time the problem is visible.
For you is possible to make a screenshot without system buffer lock?

Thank you in advance

Francesco

**Comment by mchehraz** [comment]
Hi Francesco,

What is the exact "visible" problem? Do you have any kind of lag or something?
And about the locking...I have used DirectDraw instead of Gdi32 to take screenshots for performance reasons and there is no direct "lock" operation on the system buffer in the code, I used BltFast method to copy the primary surface to a temporary one. This function (called in screenshot.cpp once) may be the only one that perform a "lock" operation on the primary surface in order to copy it's data to the destination surface. Here is the documentation for the function:

https://msdn.microsoft.com/en-us/library/windows/desktop/gg426183%28v=vs.85%29.aspx

One option would be trying to modify the flags (consider removing DDBLTFAST_WAIT for example) that are passed to the function and see if it helps. Another option would be replacing the whole screenshot code with a Gdi32 one, that approach is not as fast as current approach though.

**Comment by licarifrancesco** [comment]
Hi Mehrzad,
i see a small window lock, i tried to comment the BltFast call and with this modification the lock is removed. I tried to change the flags in BltFast call, ma the result is the same.
With 2 screens the problem is very visible.
I will try with Gdi32 thanks :)
